version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo install
  pre_build:
    commands:
      - echo pre_build     
  build:
    commands:
      - cd employee-rest-api
      - mvn clean package
      - echo build
  post_build:
    commands:
      - echo post_build
      
artifacts:
  files:
    - employee-rest-api/target/employee-rest-api-0.0.1-SNAPSHOT.jar
#    - .ebextensions/**/*
  discard-paths: yes 
  